# Site settings
title: Chess Tastic
header-img: img/home-bg.jpg
email: rafehqazi1@gmail.com
description: "Chess Made Easy"
baseurl: "/ChessTastic"
url: ""
twitter_username: RafehQ
github_username:  QaziPython
facebook_username:  ChessTastic

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor"]
